export declare const METHOD_ACCOUNT_GET_SM2_ADDRESS = "account_getSm2Address";
export declare const METHOD_ACCOUNT_GET_BALANCE = "account_getBalance";
export declare const METHOD_TX_GET_UNSIGN_DATA = "tx_getUnsignData";
export declare const METHOD_TX_SEND = "tx_sendTx";
export declare const METHOD_TX_GET_TX_BY_HASH = "tx_getTxByHash";
export declare const METHOD_BLOCK_GET_LATEST_BLOCK = "block_getLatestBlock";
export declare const METHOD_CONTRACT_GET_INPUT_DATA = "contract_getInputData";
export declare const METHOD_NODE_GET = "node_getNodes";
export declare const METHOD_DID_GET_ADDRESS = "did_getDIDAddress";
export declare const METHOD_DID_GET_REGISTER_UNSIGN_DATA = "did_getRegisterUnsignData";
export declare const METHOD_DID_SEND_REGISTER_TX = "did_sendRegisterTx";
export declare const EVENT_SUB_TX = "tx";
export declare const EVENT_SUB_BLOCK = "block";
export declare const EVENT_SUB_NETWORK = "network";
export declare const EVENT_SUB_ADDRESS = "address";
export declare const TX_OPTIONAL_TYPE_EVM = "EVM";
export declare const TX_OPTIONAL_TYPE_HVM = "HVM";
export declare const TX_OPTIONAL_TYPE_TRANSFER = "TRANSFER";
export declare const TX_OPTIONAL_FIELD_VALUE = "value";
export declare const TX_OPTIONAL_FIELD_TYPE = "type";
export declare const TX_OPTIONAL_FIELD_SIGNATURE = "signature";
export declare const TX_OPTIONAL_FIELD_EXTRA = "extra";
export declare const TX_OPTIONAL_FIELD_EXTRA_ID_64 = "extraIdInt64";
export declare const TX_OPTIONAL_FIELD_EXTRA_ID_STRING = "extraIdString";
export declare const TX_OPTIONAL_FIELD_PAYLOAD = "payload";
export declare const TX_OPTIONAL_FIELD_OP_CODE = "opCode";
export declare const TX_OPTIONAL_FIELD_HASH = "hash";
export declare enum ChainIDType {
    "RedCave" = 0
}
