export declare const METHOD_ACCOUNT_PRE_KYC = "account_preKyc";
export declare const METHOD_ACCOUNT_KYC = "account_kyc";
export declare const METHOD_ACCOUNT_CHECK_KYC = "account_checkKyc";
export declare const METHOD_ACCOUNT_GET_SM2_ADDRESS = "account_getSm2Address";
export declare const METHOD_TX_GET_UNSIGN = "tx_getUnsignTx";
export declare const METHOD_TX_SEND = "tx_sendTx";
export declare const METHOD_TX_SEND_ASYNC = "tx_sendTxAsync";
export declare const METHOD_TX_GET_RECEIPT_BY_HASH = "tx_getTxReceiptByHash";
export declare const METHOD_CONTRACT_GET_INPUT_DATA = "contract_getInputData";
export declare const METHOD_CONTRACT_GET_ABI = "contract_getAbi";
export declare const METHOD_DID_GEN_ADDRESS = "did_genDIDAddress";
export declare const METHOD_DID_GET_REGISTER_UNSIGN = "did_getRegisterUnsignTx";
export declare const METHOD_DID_GET_BY_PUBKEY = "did_getDIDByPubKey";
export declare const METHOD_DID_GET_ALL_CHAIN_ID = "did_allChainId";
export declare const METHOD_ASSET_GET_BY_DID = "asset_getByDID";
export declare const METHOD_ASSET_GET_TRANSFER_HISTORY = "asset_getTransferHis";
export declare const EVENT_SUB_TX = "tx";
export declare const EVENT_SUB_BLOCK = "block";
export declare const EVENT_SUB_NETWORK = "network";
export declare const EVENT_SUB_STATUS = "status";
export declare const EVENT_SUB_ADDRESS = "address";
export declare const TX_OPTIONAL_TYPE_EVM = "EVM";
export declare const TX_OPTIONAL_TYPE_HVM = "HVM";
export declare const TX_OPTIONAL_TYPE_TRANSFER = "TRANSFER";
export declare const TX_OPTIONAL_FIELD_FROM = "from";
export declare const TX_OPTIONAL_FIELD_TO = "to";
export declare const TX_OPTIONAL_FIELD_VALUE = "value";
export declare const TX_OPTIONAL_FIELD_TYPE = "type";
export declare const TX_OPTIONAL_FIELD_SIGNATURE = "signature";
export declare const TX_OPTIONAL_FIELD_EXTRA = "extra";
export declare const TX_OPTIONAL_FIELD_EXTRA_ID_64 = "extraIdInt64";
export declare const TX_OPTIONAL_FIELD_EXTRA_ID_STRING = "extraIdString";
export declare const TX_OPTIONAL_FIELD_EXTRA_ID_LONG = "extraIdLong";
export declare const TX_OPTIONAL_FIELD_PAYLOAD = "payload";
export declare const TX_OPTIONAL_FIELD_OP_CODE = "opCode";
export declare const TX_OPTIONAL_FIELD_HASH = "hash";
export declare const TX_OPTIONAL_FIELD_INVALID_MSG = "invalidMsg";
export declare const TX_OPTIONAL_FIELD_INVALID = "invalid";
export declare const TX_OPTIONAL_FIELD_SIMULATE = "simulate";
export declare const TX_OPTIONAL_FIELD_UNSIGN_DATA = "unsignData";
export declare const TX_OPTIONAL_FIELD_TIMESTAMP = "timestamp";
export declare const TX_OPTIONAL_FIELD_CONTRACT_NAME = "contractName";
export declare const MILLISECOND = 1;
export declare const SECOND: number;
export declare const MINUTE: number;
export declare const HOUR: number;
export declare const DAY: number;
export declare const DEFAULT_PAGE_SIZE = 10;
export declare const DEFAULT_PAGE_NUM = 1;
export declare const CHAIN_ID_REDCAVE = "RedCave";
export declare enum ChainIDType {
    CHAIN_ID_REDCAVE = "RedCave"
}
export declare const TX_SIGN_TYPE_DEFAULT_SM = "DEFAULT_SM";
export declare const TX_SIGN_TYPE_DID_SM = "DID_SM";
export declare const TX_SIGN_TYPE_ACCOUNT_SM = "ACCOUNT_SM";
export declare const TX_SIGN_TYPE_ACCOUNT_SM_PREFIX = "01";
export declare const TX_SIGN_TYPE_DID_SM_PREFIX = "81";
export declare const DID_PREFIX = "did:hpc:";
export declare const ERROR_CONNECTION_NOT_OPEN: {
    error: {
        message: string;
    };
};
